services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: parson-autogen-server
    ports:
      - "5000:5000"
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: parson-autogen-client
    ports:
      - "3000:80"
