services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: parsons-autogen-server
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: parsons-autogen-client
    ports:
      - "4000:80"
