# Build step #1: build the React front end
FROM node:16-alpine as build-step
WORKDIR client
ENV PATH /client/node_modules/.bin:$PATH
ADD client ./
RUN npm install
RUN npm run build

# Build step #2: build an nginx container
FROM nginx:stable-alpine
COPY --from=build-step /client/build /usr/share/nginx/html
COPY deployment/nginx.default.conf /etc/nginx/conf.d/default.conf
